### ISSUE TITLE
[Tracker] Season of Docs - 2022: Just links/urls: docs, planners, tickets, PRs

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/mifos-documentation#14]
## Scope

- https://mifosforge.jira.com/wiki/spaces/RES/pages/3038248961/Season+of+Docs+-+2022#proposal
- **proposal**: https://paper.dropbox.com/doc/Statement-of-Interest-Update-Platform-and-Collaboration-Documentation-for-Launch-of-Mifos-X-3.0-GSoD22--BkTM8jYcWRw8L7_aE527L6ExAg-eUmotfwsfjazWgJoHZg3n
- **diagrams from gsod'2021**: https://paper.dropbox.com/doc/Mifos-Documentation-Revision-2022--BkTHnvKz1zSTcY~rmxY19yqYAg-XVgdouRly5tJlNBfd370F
- **refs**: https://docs.google.com/document/d/1x_ucMp8O3fWwwtBCdLm_IwsO31LLg5C96LJugR-Ryec/edit#heading=h.845tlywdunr2

## Tickets

- https://github.com/openMF/android-client/issues/1877
- https://github.com/openMF/android-client/issues/1876
- https://github.com/openMF/android-client/issues/1875
- https://github.com/openMF/community-app/issues/3483
- https://github.com/openMF/community-app/issues/3482
- https://github.com/openMF/mobile-wallet/issues/1332
- https://github.com/openMF/mobile-wallet/issues/1331
- https://github.com/openMF/mifos-mobile-cn/issues/229
- https://github.com/openMF/mifos-mobile/issues/1863
- https://github.com/openMF/mobileapps.github.io/issues/1

cc @edcable.

**Comment by tapaswenipathak** [comment]
Ref: Update and refine documentation to reflect new DevOps tooling for deployment of the platform and Payment Hub EE including Terraform scripts, Configurable Helm Charts, Kubernetes and Containerization Optimations.

https://mifos.gitbook.io/docs/payment-hub-ee/overview/deployment-models/devops-tooling-for-deployment

**Comment by tapaswenipathak** [comment]
Ref: Draft new documentation on how to install, deploy and configure Payment Hub EE

- https://mifos.gitbook.io/docs/payment-hub-ee/overview/installation-instructions
- https://mifos.gitbook.io/docs/payment-hub-ee/overview/deployment-models

**Comment by tapaswenipathak** [comment]
Ref: Draft new documentation outlining functionality of payment hub, each of its new modules,  and use cases it supports 

- https://mifos.gitbook.io/docs/payment-hub-ee/business-overview/benefits-of-payment-hub-ee
- https://mifos.gitbook.io/docs/payment-hub-ee/business-overview/target-users-of-payment-hub-ee
- https://mifos.gitbook.io/docs/payment-hub-ee/overview
- https://mifos.gitbook.io/docs/payment-hub-ee/business-overview/target-users-of-payment-hub-ee

**Comment by tapaswenipathak** [comment]
Ref: Update documentation and screenshots in user manual to reflect design of new web app

- [x] Sign in page: https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/sign-in-page
- [x] Welcome page: https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/welcome-page
- [x] Dashboards page: https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/untitled
- [x] List Page: https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/list-page
- [x] Menu Page: https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/menu-page
- [ ] Form Page: https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/form-page
- [x] Clients-Groups-Centers Navigation: https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/clients-groups-centers-navigation
- [ ] Navigation Tool: https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/navigation-tool
- [x] Global Search: https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/global-search
- [ ] Loan Product and Accounting with Mifos: https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/loan-product-and-accounting-with-mifos
- [x] Reports: https://docs.mifos.org/mifosx/user-manual/for-all-users/reports
- [x] Standard Reports Shipped in Mifos X: https://docs.mifos.org/mifosx/user-manual/for-all-users/reports/standard-reports-shipped-in-mifos-x
- [x] Standard Reports Field Descriptions: https://docs.mifos.org/mifosx/user-manual/for-all-users/reports/standard-reports-field-descriptions
- [x] Custom Reports: https://docs.mifos.org/mifosx/user-manual/for-all-users/reports/custom-reports
- [ ] XBRL Reporting: https://docs.mifos.org/mifosx/user-manual/for-all-users/reports/xbrl-reporting
- [x] Reports: https://docs.mifos.org/mifosx/user-manual/for-all-users/reports
- [x] Initial System Set Up: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/initial-system-set-up
- [x] Administration: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/administration
- [x] Organization: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/administration/organization
- [x] System: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/administration/system
- [x] Products: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/administration/products
- [x] Templates: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/administration/templates
- [x] mifos dropdown: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/administration/mifos-dropdown
- [x] Clients-Groups-Centers Navigation: https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/clients-groups-centers-navigation
- [x] Clients, Groups and Centers: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/clients-groups-and-centers
- [x] Manage Clients: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/clients-groups-and-centers/manage-clients
- [ ] Client Relationship Management: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/clients-groups-and-centers/manage-clients/client-relationship-management
- [ ] Manage Groups: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/clients-groups-and-centers/manage-groups
- [ ] Manage Centers: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/clients-groups-and-centers/manage-centers
- [x] Accounting: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/accounting
- [ ] Chart of Accounts - General Ledger Setup: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/accounting/chart-of-accounts-general-ledger-setup
- [ ] Accounts linked to Financial Activities: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/accounting/accounts-linked-to-financial-activities
- [ ] Migrate opening balances (Office-wise): https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/accounting/migrate-opening-balances-office-wise
- [ ] Accounting Rules: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/accounting/accounting-rules
- [ ] Provisioning Entries: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/accounting/provisioning-entries
- [ ] Print General Ledger Listing: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/accounting/print-general-ledger-listing
- [ ] How To Enter GL Opening Balance: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/accounting/how-to-enter-gl-opening-balance
- [ ] Configure Notifications: https://docs.mifos.org/mifosx/user-manual/for-administrators-mifos-x-platform/configure-notifications
- [ ] Add Journal Entries: https://docs.mifos.org/mifosx/user-manual/for-operational-users-mifos-x-web-app/accounting-operations/add-journal-entries
- [ ] Searching Accounting Transactions: https://docs.mifos.org/mifosx/user-manual/for-operational-users-mifos-x-web-app/accounting-operations/searching-accounting-transactions
- [ ] Frequent Postings: https://docs.mifos.org/mifosx/user-manual/for-operational-users-mifos-x-web-app/accounting-operations/frequent-postings
- [ ] Advanced Accounting Rules: https://docs.mifos.org/mifosx/user-manual/for-operational-users-mifos-x-web-app/accounting-operations/advanced-accounting-rules
- [ ] Closing Entries: https://docs.mifos.org/mifosx/user-manual/for-operational-users-mifos-x-web-app/accounting-operations/closing-entries
- [ ] Accruals: https://docs.mifos.org/mifosx/user-manual/for-operational-users-mifos-x-web-app/accounting-operations/accruals
- [ ] Deposit Accounts: https://docs.mifos.org/mifosx/user-manual/for-operational-users-mifos-x-web-app/accounts-and-transactions/deposit-accounts
- [ ] Loan Accounts: https://docs.mifos.org/mifosx/user-manual/for-operational-users-mifos-x-web-app/accounts-and-transactions/loan-accounts
- [ ] Overdraft account: https://docs.mifos.org/mifosx/user-manual/for-operational-users-mifos-x-web-app/accounts-and-transactions/overdraft-account
- [ ] Saving Accounts: https://docs.mifos.org/mifosx/user-manual/for-operational-users-mifos-x-web-app/accounts-and-transactions/saving-accounts
- [ ] Share Accounts: https://docs.mifos.org/mifosx/user-manual/for-operational-users-mifos-x-web-app/accounts-and-transactions/share-accounts
- [ ] Checker Inbox & Tasks: https://docs.mifos.org/mifosx/user-manual/for-operational-users-mifos-x-web-app/checker-inbox-and-tasks
- [x] Side Bar - Features: https://docs.mifos.org/mifosx/user-manual/side-bar-features
- [x] Checker inbox and tasks: https://docs.mifos.org/mifosx/user-manual/side-bar-features/checker-inbox-and-tasks
- [ ] Collection sheet: https://docs.mifos.org/mifosx/user-manual/side-bar-features/collection-sheet
- [x] Help.: https://docs.mifos.org/mifosx/user-manual/others-mifos-dropdown/help
- [x] Individual collection sheet: https://docs.mifos.org/mifosx/user-manual/side-bar-features/individual-collection-sheet
- [x] Keyboard short-cuts: https://docs.mifos.org/mifosx/user-manual/side-bar-features/keyboard-short-cuts
- [x] Navigation: https://docs.mifos.org/mifosx/user-manual/side-bar-features/navigation
- [x] Others - mifos dropdown: https://docs.mifos.org/mifosx/user-manual/others-mifos-dropdown
- [x] Profile: https://docs.mifos.org/mifosx/user-manual/others-mifos-dropdown/profile
- [x] Settings: https://docs.mifos.org/mifosx/user-manual/others-mifos-dropdown/settings
- [x] Date format: https://docs.mifos.org/mifosx/user-manual/others-mifos-dropdown/settings/date-format
- [x] Language: https://docs.mifos.org/mifosx/user-manual/others-mifos-dropdown/settings/language
- [x] Signout: https://docs.mifos.org/mifosx/user-manual/others-mifos-dropdown/signout
